// Code generated by MockGen. DO NOT EDIT.
// Source: domain/contracts/pubsub.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIPubSub is a mock of IPubSub interface.
type MockIPubSub struct {
	ctrl     *gomock.Controller
	recorder *MockIPubSubMockRecorder
}

// MockIPubSubMockRecorder is the mock recorder for MockIPubSub.
type MockIPubSubMockRecorder struct {
	mock *MockIPubSub
}

// NewMockIPubSub creates a new mock instance.
func NewMockIPubSub(ctrl *gomock.Controller) *MockIPubSub {
	mock := &MockIPubSub{ctrl: ctrl}
	mock.recorder = &MockIPubSubMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPubSub) EXPECT() *MockIPubSubMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockIPubSub) Publish(stream string, message map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", stream, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockIPubSubMockRecorder) Publish(stream, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockIPubSub)(nil).Publish), stream, message)
}
