CREATE TABLE todo_items (
  id CHAR(36) PRIMARY KEY,
  description TEXT NOT NULL,
  due_date DATETIME NULL,
  file_id VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);